export const FICHE_AVANCEMENT_MARGIN_V_MM = 6
export const FICHE_AVANCEMENT_MARGIN_H_MM = 7
export const FICHE_AVANCEMENT_PRINT_MIN_SCALE = 0.58
export const FICHE_AVANCEMENT_PRINT_FILL_RATIO = 0.97
export const FICHE_AVANCEMENT_PRINT_MAX_SCALE = 1.12
